// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*! 
 * @file message.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace { char dummy; }
#endif

#include "message.h"

#include <fastcdr/Cdr.h>

#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

Message::Message()
{
    m_index = 0;

}

Message::~Message()
{
}

Message::Message(const Message &x)
{
    m_index = x.m_index;
    m_text = x.m_text;
}

Message::Message(Message &&x)
{
    m_index = x.m_index;
    m_text = std::move(x.m_text);
}

Message& Message::operator=(const Message &x)
{
    m_index = x.m_index;
    m_text = x.m_text;
    
    return *this;
}

Message& Message::operator=(Message &&x)
{
    m_index = x.m_index;
    m_text = std::move(x.m_text);
    
    return *this;
}

size_t Message::getMaxCdrSerializedSize(size_t current_alignment)
{
    size_t initial_alignment = current_alignment;
            
    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);

    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4) + 255 + 1;


    return current_alignment - initial_alignment;
}

size_t Message::getCdrSerializedSize(const Message& data, size_t current_alignment)
{
    size_t initial_alignment = current_alignment;
            
    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);

    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4) + data.text().size() + 1;


    return current_alignment - initial_alignment;
}

void Message::serialize(eprosima::fastcdr::Cdr &scdr) const
{
    scdr << m_index;

    if(m_text.length() <= 255)
    scdr << m_text;
    else
        throw eprosima::fastcdr::exception::BadParamException("text field exceeds the maximum length");
}

void Message::deserialize(eprosima::fastcdr::Cdr &dcdr)
{
    dcdr >> m_index;
    dcdr >> m_text;
}

size_t Message::getKeyMaxCdrSerializedSize(size_t current_alignment)
{
	size_t current_align = current_alignment;
            



    return current_align;
}

bool Message::isKeyDefined()
{
    return false;
}

void Message::serializeKey(eprosima::fastcdr::Cdr &scdr) const
{
	 
	 
}